parameters:

imports:
    - { resource: 'services/human_resources.yaml' }
    - { resource: 'services/payroll.yaml' }
    - { resource: 'services/shared_kernel.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
